{"uid":"b1b0ee3c6e7b88e3","name":"test_login_with_wrong_username_and_password","fullName":"test_manual_login#test_login_with_wrong_username_and_password","historyId":"7017f6085a332addf37f806293a8f842","time":{"start":1727671992304,"stop":1727672024150,"duration":31846},"status":"broken","statusMessage":"selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5\nNoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:511:5\ndom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16","statusTrace":"driver = <selenium.webdriver.firefox.webdriver.WebDriver (session=\"edf7cf8d-5c86-460f-b044-de6d00b69417\")>\n\n    def test_login_with_wrong_username_and_password(driver):\n        logging.info(\"Starting test_login_with_wrong_username_and_password\")\n        try:\n            login_page(driver)\n            logging.info(\"Opened login page\")\n            driver.find_element(By.XPATH, User_Input_Xpath).send_keys(user_name)\n            driver.find_element(By.XPATH, Password_Input_Xpath).send_keys(user_password)\n            driver.find_element(By.XPATH, Login_Button_Xpath).click()\n    \n            WebDriverWait(driver, 10).until(\n                EC.presence_of_element_located((By.XPATH, \"//strong[normalize-space()='Error']\"))\n            )\n            alert_text = driver.find_element(By.XPATH, \"//strong[normalize-space()='Error']\").text\n            logging.info(f\"Login alert text found: {alert_text}\")\n    \n            assert alert_text == \"Error\"\n            logging.info(\"Invalid login test passed\")\n        except Exception as e:\n            logging.error(f\"Test failed with error: {e}\")\n            take_screenshot(driver, \"test_login_with_wrong_username_and_password\")\n>           raise e\n\ntest_manual_login.py:163: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\ntest_manual_login.py:152: in test_login_with_wrong_username_and_password\n    WebDriverWait(driver, 10).until(\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"edf7cf8d-5c86-460f-b044-de6d00b69417\")>\nmethod = <function presence_of_element_located.<locals>._predicate at 0x000002566E0EF560>, message = ''\n\n    def until(self, method: Callable[[D], Union[Literal[False], T]], message: str = \"\") -> T:\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value does not evaluate to ``False``.\n    \n        :param method: callable(WebDriver)\n        :param message: optional message for :exc:`TimeoutException`\n        :returns: the result of the last call to `method`\n        :raises: :exc:`selenium.common.exceptions.TimeoutException` if timeout occurs\n        \"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.monotonic() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, \"screen\", None)\n                stacktrace = getattr(exc, \"stacktrace\", None)\n            time.sleep(self._poll)\n            if time.monotonic() > end_time:\n                break\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message: \nE       Stacktrace:\nE       RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nE       WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5\nE       NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:511:5\nE       dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16\n\nautomation\\Lib\\site-packages\\selenium\\webdriver\\support\\wait.py:105: TimeoutException","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":1,"retriesStatusChange":false,"beforeStages":[{"name":"driver","time":{"start":1727671984795,"stop":1727671992304,"duration":7509},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false,"stepsCount":0}],"testStage":{"status":"broken","statusMessage":"selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5\nNoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:511:5\ndom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16","statusTrace":"driver = <selenium.webdriver.firefox.webdriver.WebDriver (session=\"edf7cf8d-5c86-460f-b044-de6d00b69417\")>\n\n    def test_login_with_wrong_username_and_password(driver):\n        logging.info(\"Starting test_login_with_wrong_username_and_password\")\n        try:\n            login_page(driver)\n            logging.info(\"Opened login page\")\n            driver.find_element(By.XPATH, User_Input_Xpath).send_keys(user_name)\n            driver.find_element(By.XPATH, Password_Input_Xpath).send_keys(user_password)\n            driver.find_element(By.XPATH, Login_Button_Xpath).click()\n    \n            WebDriverWait(driver, 10).until(\n                EC.presence_of_element_located((By.XPATH, \"//strong[normalize-space()='Error']\"))\n            )\n            alert_text = driver.find_element(By.XPATH, \"//strong[normalize-space()='Error']\").text\n            logging.info(f\"Login alert text found: {alert_text}\")\n    \n            assert alert_text == \"Error\"\n            logging.info(\"Invalid login test passed\")\n        except Exception as e:\n            logging.error(f\"Test failed with error: {e}\")\n            take_screenshot(driver, \"test_login_with_wrong_username_and_password\")\n>           raise e\n\ntest_manual_login.py:163: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\ntest_manual_login.py:152: in test_login_with_wrong_username_and_password\n    WebDriverWait(driver, 10).until(\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"edf7cf8d-5c86-460f-b044-de6d00b69417\")>\nmethod = <function presence_of_element_located.<locals>._predicate at 0x000002566E0EF560>, message = ''\n\n    def until(self, method: Callable[[D], Union[Literal[False], T]], message: str = \"\") -> T:\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value does not evaluate to ``False``.\n    \n        :param method: callable(WebDriver)\n        :param message: optional message for :exc:`TimeoutException`\n        :returns: the result of the last call to `method`\n        :raises: :exc:`selenium.common.exceptions.TimeoutException` if timeout occurs\n        \"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.monotonic() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, \"screen\", None)\n                stacktrace = getattr(exc, \"stacktrace\", None)\n            time.sleep(self._poll)\n            if time.monotonic() > end_time:\n                break\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message: \nE       Stacktrace:\nE       RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nE       WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5\nE       NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:511:5\nE       dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16\n\nautomation\\Lib\\site-packages\\selenium\\webdriver\\support\\wait.py:105: TimeoutException","steps":[],"attachments":[{"uid":"fadfcfd2344d4093","name":"test_login_with_wrong_username_and_password","source":"fadfcfd2344d4093.png","type":"image/png","size":481132},{"uid":"23a0e5480882913","name":"Test Log","source":"23a0e5480882913.txt","type":"text/plain","size":0},{"uid":"aa537b8a5d77af61","name":"log","source":"aa537b8a5d77af61.txt","type":"text/plain","size":385}],"parameters":[],"shouldDisplayMessage":true,"attachmentsCount":3,"hasContent":true,"attachmentStep":false,"stepsCount":0},"afterStages":[{"name":"driver::0","time":{"start":1727672024165,"stop":1727672027239,"duration":3074},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false,"stepsCount":0}],"labels":[{"name":"suite","value":"test_manual_login"},{"name":"host","value":"DESKTOP-G36OV76"},{"name":"thread","value":"13352-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"test_manual_login"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[{"uid":"fb9a2f1979b070c3","status":"broken","statusDetails":"selenium.common.exceptions.WebDriverException: Message: Failed to decode response from marionette","time":{"start":1727671664232,"stop":1727671664232,"duration":0}}],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"tags":[]},"source":"b1b0ee3c6e7b88e3.json","parameterValues":[]}